################################################################################
# File used by AWS codebuild to get build instructions
################################################################################

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
      - IMAGE_TAG=$(openssl rand -hex 8)
      # - IMAGE_TAG=$(git log -n 1 --oneline | awk {'print $1'})
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build --build-arg PORT=$PORT -t $AWS_ECR_URL:latest .
      - docker tag $AWS_ECR_URL:latest $AWS_ECR_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_URL:latest
      - docker push $AWS_ECR_URL:$IMAGE_TAG