name: terraform_deploy_to_aws

on:
  push:
    branches: [ "dev" ]

jobs:
  build_plan_apply:
    name: build_plan_apply
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    defaults:
      run:
        working-directory: "./terraform"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2


    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=${{ secrets.TF_STATE_KEY }}" -backend-config="region=${{ secrets.TF_STATE_REGION }}"
      continue-on-error: false

    - name: Terraform Validate
      id: validate
      run: terraform validate
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      env:
        TF_VAR_domain_name : ${{ secrets.TF_VAR_DOMAIN_NAME }}
        TF_VAR_project     : ${{ secrets.TF_VAR_PROJECT }}
        TF_VAR_region      : ${{ secrets.TF_VAR_REGION }}
        TF_VAR_env         : ${{ github.ref_name }}
      run: terraform plan -out=terraform.plan
      continue-on-error: false

    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.6.0
      with:
        approvers: apanchev
        secret: ${{ github.TOKEN }}
        minimum-approvals: 1

    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve terraform.plan
      continue-on-error: false
